### ISSUE TITLE
#1后手机端快捷键的布局很丑

### ISSUE THREAD

**Issue by Tisfy** [LetMeFly666/PressByWeb#3]
![image](https://github.com/LetMeFly666/PressByWeb/assets/88925368/31216705-7c3c-49a6-b4fc-17504021b9ae)

👆updates by #1

**Comment by Tisfy** [comment]
![手机端](https://github.com/LetMeFly666/PressByWeb/assets/56995506/a5f0b586-547c-4e3a-a84b-ff72ab908e27)

**Comment by LetMeFly666** [comment]
![手机端](https://github.com/LetMeFly666/PressByWeb/assets/56995506/1944c19c-3217-4c73-88b9-c5b34bcf2f30)
